name: Build and Deploy CleverQ

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: npm run build

      - name: Archive Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: cleverq-build
          path: ./

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Build Artifacts
        uses: actions/download-artifact@v3
        with:
          name: cleverq-build

      - name: Deploy to Server
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
        run: |
          echo "${{ secrets.SSH_KEY }}" > private_key && chmod 600 private_key
          rsync -avz -e "ssh -i private_key" ./ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/var/www/cleverq
